package com.websystique.springmvc.model;
// Generated 23-ott-2018 21.38.35 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Portafoglio generated by hbm2java
 */
@Entity
@Table(name = "PORTAFOGLIO", schema = "PUBLIC", catalog = "PUBLIC")
public class Portafoglio implements java.io.Serializable {

	private Integer portafoglioId;
	private Titolo titolo;
	private Double quantita;
	private Date dataAcquisto;
	private Double prezzoAcquisto;
	private Double tassoValutaAcquisto;
	private Date dataVendita;
	private Double prezzoVendita;
	private Double tassoValutaVendita;
	private Double controvaloreEuro;

	public Portafoglio() {
	}

	public Portafoglio(Titolo titolo, Double quantita, Date dataAcquisto, Double prezzoAcquisto,
			Double tassoValutaAcquisto, Date dataVendita, Double prezzoVendita, Double tassoValutaVendita,
			Double controvaloreEuro) {
		this.titolo = titolo;
		this.quantita = quantita;
		this.dataAcquisto = dataAcquisto;
		this.prezzoAcquisto = prezzoAcquisto;
		this.tassoValutaAcquisto = tassoValutaAcquisto;
		this.dataVendita = dataVendita;
		this.prezzoVendita = prezzoVendita;
		this.tassoValutaVendita = tassoValutaVendita;
		this.controvaloreEuro = controvaloreEuro;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PORTAFOGLIO_ID", unique = true, nullable = false)
	public Integer getPortafoglioId() {
		return this.portafoglioId;
	}

	public void setPortafoglioId(Integer portafoglioId) {
		this.portafoglioId = portafoglioId;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
	@ManyToOne
	@JoinColumn(name = "TITOLO_ID")
	public Titolo getTitolo() {
		return this.titolo;
	}

	public void setTitolo(Titolo titolo) {
		this.titolo = titolo;
	}

	@Column(name = "QUANTITA", precision = 64, scale = 0)
	public Double getQuantita() {
		return this.quantita;
	}

	public void setQuantita(Double quantita) {
		this.quantita = quantita;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_ACQUISTO", length = 10)
	public Date getDataAcquisto() {
		return this.dataAcquisto;
	}

	public void setDataAcquisto(Date dataAcquisto) {
		this.dataAcquisto = dataAcquisto;
	}

	@Column(name = "PREZZO_ACQUISTO", precision = 64, scale = 0)
	public Double getPrezzoAcquisto() {
		return this.prezzoAcquisto;
	}

	public void setPrezzoAcquisto(Double prezzoAcquisto) {
		this.prezzoAcquisto = prezzoAcquisto;
	}

	@Column(name = "TASSO_VALUTA_ACQUISTO", precision = 64, scale = 0)
	public Double getTassoValutaAcquisto() {
		return this.tassoValutaAcquisto;
	}

	public void setTassoValutaAcquisto(Double tassoValutaAcquisto) {
		this.tassoValutaAcquisto = tassoValutaAcquisto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATA_VENDITA", length = 10)
	public Date getDataVendita() {
		return this.dataVendita;
	}

	public void setDataVendita(Date dataVendita) {
		this.dataVendita = dataVendita;
	}

	@Column(name = "PREZZO_VENDITA", precision = 64, scale = 0)
	public Double getPrezzoVendita() {
		return this.prezzoVendita;
	}

	public void setPrezzoVendita(Double prezzoVendita) {
		this.prezzoVendita = prezzoVendita;
	}

	@Column(name = "TASSO_VALUTA_VENDITA", precision = 64, scale = 0)
	public Double getTassoValutaVendita() {
		return this.tassoValutaVendita;
	}

	public void setTassoValutaVendita(Double tassoValutaVendita) {
		this.tassoValutaVendita = tassoValutaVendita;
	}

	@Column(name = "CONTROVALORE_EURO", precision = 64, scale = 0)
	public Double getControvaloreEuro() {
		return this.controvaloreEuro;
	}

	public void setControvaloreEuro(Double controvaloreEuro) {
		this.controvaloreEuro = controvaloreEuro;
	}

}
