package com.websystique.springmvc.model;
// Generated 23-ott-2018 21.38.35 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Titolo generated by hbm2java
 */
@Entity
@Table(name = "TITOLO", schema = "PUBLIC", catalog = "PUBLIC")
public class Titolo implements java.io.Serializable {

	private Integer titoloId;
	private Mercato mercato;
	private Valuta valuta;
	private String isin;
	private String denominazione;
	private Set<Portafoglio> portafoglios = new HashSet<Portafoglio>(0);

	public Titolo() {
	}

	public Titolo(Mercato mercato, Valuta valuta, String isin, String denominazione) {
		this.mercato = mercato;
		this.valuta = valuta;
		this.isin = isin;
		this.denominazione = denominazione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TITOLO_ID", unique = true, nullable = false)
	public Integer getTitoloId() {
		return this.titoloId;
	}

	public void setTitoloId(Integer titoloId) {
		this.titoloId = titoloId;
	}

//	@ManyToOne(fetch = FetchType.EAGER)
	@ManyToOne
	@JoinColumn(name = "MERCATO_ID")
	public Mercato getMercato() {
		return this.mercato;
	}

	public void setMercato(Mercato mercato) {
		this.mercato = mercato;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
	@ManyToOne
	@JoinColumn(name = "VALUTA_ID")
	public Valuta getValuta() {
		return this.valuta;
	}

	public void setValuta(Valuta valuta) {
		this.valuta = valuta;
	}

	@Column(name = "ISIN", length = 10)
	public String getIsin() {
		return this.isin;
	}

	public void setIsin(String isin) {
		this.isin = isin;
	}

	@Column(name = "DENOMINAZIONE", length = 30)
	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titolo")
	@OneToMany(mappedBy = "titolo")
	public Set<Portafoglio> getPortafoglios() {
		return this.portafoglios;
	}

	public void setPortafoglios(Set<Portafoglio> portafoglios) {
		this.portafoglios = portafoglios;
	}
}
